use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :block_scout_api, BlockScoutApi.Endpoint,
  force_ssl: false,
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  check_origin: System.get_env("CHECK_ORIGIN") || false,
  http: [port: System.get_env("API_PORT")],
  url: [
    scheme: "https",
    port: System.get_env("API_PORT"),
    host: System.get_env("BLOCKSCOUT_HOST") || "localhost",
    path: System.get_env("NETWORK_PATH") || "/"
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :logger, :block_scout_api,
  level: :info,
  path: Path.absname("logs/prod/block_scout_api.log"),
  rotate: %{max_bytes: 52_428_800, keep: 19}
