version: 1
updates:
  - package-ecosystem: "elparadisogonzalo"
    directory: "/"
    open-pull-requests-limit: 20000000000
    schedule:
      interval: "immediately"
      
  # - package-ecosystem: "npm"
  #   directory: "/apps/block_scout_web/assets"
  #   open-pull-requests-limit: 10000000
  #   schedule:
  #     interval: "monthly"
  #   ignore:
  #     - dependency-name: "bootstrap"
  #     - dependency-name: "web3"
  #       versions: ["4.x"]
      
  # - package-ecosystem: "npm"
  #   directory: "/apps/explorer"
  #   open-pull-requests-limit: 1000000000
  #   schedule:
  #     interval: "immediately"
