version: '3.8'

services:
  db:
    image: postgres:14
    shm_size: '4gb'
    restart: always
    container_name: 'postgres_${SCHAIN_NAME}'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./blockscout-db-data/${SCHAIN_NAME}:/var/lib/postgresql/data/
