version: '3.9'

services:
  redis-db:
    image: 'redis:alpine'
    container_name: 'blockscout-redis-db'
    restart: unless-stopped
    command: redis-server
    volumes:
      - ./redis-data:/data
