version: '3.9'

services:
  stats:
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'stats-luxnet'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-stats.env
    environment:
      - STATS__DB_URL=postgresql://lux:oi1dAc9bad8MSc2da51a2544f0cb8e16lb21A@host-postgres:5432/stats_luxnet
      - STATS__BLOCKSCOUT_DB_URL=postgresql://lux:oi1dAc9bad8MSc2da51a2544f0cb8e16lb21A@host-postgres:5432/explorer_luxnet
      - STATS__CREATE_DATABASE=${STATS__CREATE_DATABASE:-false}
      - STATS__RUN_MIGRATIONS=${STATS__RUN_MIGRATIONS:-false}
