version: '3.8'

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  backend:
    depends_on:
      - smart-contract-verifier
      - redis_db
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "true"
        DISABLE_WEBAPP: "true"
        API_V1_WRITE_METHODS_DISABLED: "true"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.2.0
    restart: always
    container_name: 'blockscout'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout-sepolia.env
    environment:
      API_V2_ENABLED: 'true'
      ETHEREUM_JSONRPC_HTTP_URL: 'https://tmp-api.sepolia.kroma.network/'
      CHAIN_ID: '2358'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      INDEXER_OPTIMISM_L1_RPC: 'https://rpc.sepolia.org'
      INDEXER_OPTIMISM_L1_BATCH_START_BLOCK: '3834891'
      INDEXER_OPTIMISM_L1_BATCH_INBOX: '0xfa79000000000000000000000000000000000001'
      INDEXER_OPTIMISM_L1_BATCH_SUBMITTER: '0xf15dc770221b99c98d4aaed568f2ab04b9d16e42'
      INDEXER_OPTIMISM_L1_PORTAL_CONTRACT: '0x31ab8eD993A3BE9Aa2757C7D368Dc87101A868a4'
      INDEXER_OPTIMISM_L1_OUTPUT_ROOTS_START_BLOCK: '3834891'
      INDEXER_OPTIMISM_L1_OUTPUT_ORACLE_CONTRACT: '0x7291913342063fd10d31651735BAF3877D2F9645'
      INDEXER_OPTIMISM_L1_WITHDRAWALS_START_BLOCK: '3834891'
      INDEXER_OPTIMISM_L2_WITHDRAWALS_START_BLOCK: '1'
      INDEXER_OPTIMISM_L2_MESSAGE_PASSER_CONTRACT: '0x4200000000000000000000000000000000000003'
      INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK: '3834891'
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  stats:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats