version: '3.8'

services:
  db:
    extends:
      file: ./services/docker-compose-db-skale.yml
      service: db

  blockscout:
    depends_on:
      - db
    image: skalenetwork/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.1.4
    restart: always
    stop_grace_period: 1m
    container_name: 'blockscout_${SCHAIN_NAME}'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      LOGO: "/images/skale_logo.png"
      SUBNETWORK: ${SCHAIN_NAME}
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_HTTP_URL: ${ENDPOINT}
      ETHEREUM_JSONRPC_WS_URL: ${WS_ENDPOINT}
      DATABASE_URL: postgresql://postgres:@host.docker.internal:${DB_PORT}/blockscout?ssl=false
      FIRST_BLOCK: ${FIRST_BLOCK:-0}
      NETWORK: "SKALE"
      INDEXER_RECEIPTS_BATCH_SIZE: 128
      INDEXER_COIN_BALANCES_BATCH_SIZE: 128
      POOL_SIZE: 130
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
      INDEXER_DISABLE_BLOCK_REWARD_FETCHER: "true"
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER: "true"
      INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER: "true"
      ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES: "true"
      INDEXER_CATCHUP_BLOCK_INTERVAL: "3s"
      TXS_STATS_ENABLED: "false"
      APPS_MENU: "false"
      INDEXER_HIDE_INDEXING_PROGRESS_ALERT: "true"
      CHAIN_SPEC_PATH: "/opt/app/config.json"
      COIN: "ETH"
      SECRET_KEY_BASE: "RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5"
      CHAIN_ID: ${CHAIN_ID}
      RE_CAPTCHA_DISABLED: "true"
    ports:
      - ${PORT}:4000
    volumes:
      - ${SCHAIN_DATA_DIR:-./blockscout-data}/logs:/app/logs/
      - ${CONFIG_PATH:-./}:/opt/app/config.json

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier-skale.yml
      service: smart-contract-verifier
