apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  annotations:
  name: quai-blockscout-dev
  namespace: quai-dev
spec:
  domains:
  - dev.prime.quaiscan.io
  - dev.cyprus.quaiscan.io
  - dev.paxos.quaiscan.io
  - dev.hydra.quaiscan.io
  - dev.cyprus1.quaiscan.io
  - dev.cyprus2.quaiscan.io
  - dev.cyprus3.quaiscan.io
  - dev.paxos1.quaiscan.io
  - dev.paxos2.quaiscan.io
  - dev.paxos3.quaiscan.io
  - dev.hydra1.quaiscan.io
  - dev.hydra2.quaiscan.io
  - dev.hydra3.quaiscan.io
