name: 'Setup repo'
description: 'Setup repo: checkout/login/extract metadata, Set up Docker Buildx'
inputs:
  docker-username:
    description: 'Docker username'
    required: true
  docker-password:
    description: 'Docker password'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: blockscout/blockscout