name: GitHub Builder Production

on:
  workflow_dispatch:
    inputs:
      environment:
          description: 'Target Deploy Environment'
          type: string
          required: true
          default: 'production'
      configPath:
          description: 'Declarative Manifest Path'
          type: string
          required: true
          default: 'config'

env:
  ENVIRONMENT: 'production'
  CONFIG_PATH: 'config'
  GIT_USERNAME: ${{ github.actor }}
  GIT_EMAIL: 'github-actions@github.com'
  PA_TOKEN: ${{ secrets.GHA_PAT }}

jobs:
  build-and-push-deploy:
    permissions:
      contents: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: cloudwalk/github-builder
        path: ./github-builder
        token: ${{ secrets.GHA_PAT }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: cloudwalk/monorepo-gitops
        path: ./monorepo-gitops
        token: ${{ secrets.GHA_PAT }}
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
          workload_identity_provider: 'projects/390402527997/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions@infinitepay-mainnet.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud auth configure-docker'
    - name: 'GitHub Builder'
      run:  |
        echo "monorepo-gitops" >> .dockerignore
        echo "github-builder" >> .dockerignore
        pip3 install -r ./github-builder/requirements.txt
        python3 ./github-builder/src/main.py
