name: Pre-release for Optimism

on:
  workflow_dispatch:
    inputs:
      number:
        type: number
        required: true

env:
  OTP_VERSION: ${{ vars.OTP_VERSION }}
  ELIXIR_VERSION: ${{ vars.ELIXIR_VERSION }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ vars.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Optimism (indexer + API)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-optimism:${{ env.RELEASE_VERSION }}-alpha.${{ inputs.number }}
          platforms: |
            linux/amd64
          build-args: |
            DISABLE_WEBAPP=false
            API_V1_READ_METHODS_DISABLED=false
            API_V1_WRITE_METHODS_DISABLED=false
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-alpha.${{ inputs.number }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism

      - name: Build and push Docker image for Optimism (indexer)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-optimism:${{ env.RELEASE_VERSION }}-alpha.${{ inputs.number }}-indexer
          platforms: |
            linux/amd64
          build-args: |
            DISABLE_API=true
            DISABLE_WEBAPP=true
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-alpha.${{ inputs.number }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism

      - name: Build and push Docker image for Optimism (API)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: blockscout/blockscout-optimism:${{ env.RELEASE_VERSION }}-alpha.${{ inputs.number }}-api
          platforms: |
            linux/amd64
          build-args: |
            DISABLE_INDEXER=true
            DISABLE_WEBAPP=true
            CACHE_EXCHANGE_RATES_PERIOD=
            CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            ADMIN_PANEL_ENABLED=false
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-alpha.${{ inputs.number }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism