name: Release for Celo

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  OTP_VERSION: '27.3.4.6'
  ELIXIR_VERSION: '1.19.4'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: build
    env:
      RELEASE_VERSION: 10.0.1
      API_GRAPHQL_MAX_COMPLEXITY: 10400
    steps:
      - uses: actions/checkout@v5
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-remote-multi-platform: true
          docker-arm-host: ${{ secrets.ARM_RUNNER_HOSTNAME }}
          docker-arm-host-key: ${{ secrets.ARM_RUNNER_KEY }}

      - name: Build and push Docker image for CELO (indexer + API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/blockscout/blockscout-celo-private:latest, ghcr.io/blockscout/blockscout-celo-private:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            API_GRAPHQL_MAX_COMPLEXITY=${{ env.API_GRAPHQL_MAX_COMPLEXITY }}
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism-celo

      - name: Build and push Docker image for CELO (indexer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/blockscout/blockscout-celo-private:${{ env.RELEASE_VERSION }}-indexer
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            API_GRAPHQL_MAX_COMPLEXITY=${{ env.API_GRAPHQL_MAX_COMPLEXITY }}
            DISABLE_API=true
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism-celo
