name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Merge upstream
        run: |
          git remote add upstream https://github.com/blockscout/blockscout.git
          git fetch upstream develop
          git checkout develop
          git merge upstream/develop
          git push origin develop